### ISSUE TITLE
unknown status

### ISSUE THREAD

**Issue by tarbax** [pippyn/Home-Assistant-Sensor-Ophaalkalender#13]
![image](https://user-images.githubusercontent.com/34491557/70570531-5e599a00-1b9c-11ea-974c-2d3b9cccd549.png)
![image](https://user-images.githubusercontent.com/34491557/70570546-64e81180-1b9c-11ea-85c4-bdf510e0925b.png)

```
- platform: ophaalkalender
  resources:
    - GFT
    - Restafval
    - papier
    - pmd
    - grof huisvuil
    - Glas
    - Textiel
  postcode: xxxx
  streetname: xxxxxxxxxx
  streetnumber: xxx
```
