### ISSUE TITLE
time formatting & resource

### ISSUE THREAD

**Issue by Mikomie** [pippyn/Home-Assistant-Sensor-Ophaalkalender#23]
Hi there,
great work ! thanks !
I did notice 2 issues:
The resource for "tuinafval" is actualy "groenafval" now, perhaps they changed it?
If i change the date formatting it only works for "grof aval".

```
# ophaalkalender - afvalkalender
  - platform: ophaalkalender
    resources:
      - restafval
      - tuinafval
      - groenafval
      - papier
      - pmd
      - grofafval
    postcode: 8310
    streetname: Astridlaan
    streetnumber: 111
    dateformat: '%d %b'
    #dateonly: 1
```
